import type { Metadata } from "next";
import "./globals.css";
import { Poppins, Gothic_A1, Ruda } from "next/font/google";

const poppins = Poppins({
	subsets: ["latin"],
	variable: "--font-poppins",
	display: "swap",
	weight: "400",
});

const gothic = Gothic_A1({
	subsets: ["latin"],
	variable: "--font-gothic",
	display: "swap",
	weight: "400",
});

const ruda = Ruda({
	subsets: ["latin"],
	variable: "--font-ruda",
	display: "swap",
	weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body
				className={`${poppins.variable} ${gothic.variable} ${ruda.variable}  antialiased`}>
				{children}
			</body>
		</html>
	);
}
